export * from './start.page';
export * from './home/home.page';
export * from './welcome/welcome.page';
export * from './profilePage/profile.page';
export * from './createChild/createChild.page';
export * from './createParent/createParent.page';
export * from './createAccount/createAccount.page';
export * from './createTransaction/createTransaction.page';
export * from './createRecurringTransaction/createRecurringTransaction.page';
